# Generated by Django 2.2.4 on 2019-08-03 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='著者名')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
            },
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.ManyToManyField(null=True, to='todo.Author', verbose_name='著者'),
        ),
    ]
